In [1]:
import torch

In [18]:
t = torch.arange(10, 14)
t

tensor([10, 11, 12, 13])

In [34]:
index = torch.tensor([True, True, False, False])
t[index]= torch.tensor([1, 1])
t

tensor([ 1,  1, 12, 13])

In [53]:
d = {1: None}
d.pop(0, None)
d

{1: None}

In [58]:
torch.empty(100, dtype=torch.int8)

tensor([ 48, 102,  42,   5,   0,   0,   0,   0, -16,  71,  -8,   3,   0,   0,
          0,   0, -32, -27,  29, -97, -55, 127,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0], dtype=torch.int8)