In [2]:
import os
import sys

module_path = os.path.abspath('/home/gangda/workspace/graph_engine/test/pprgo')
if module_path not in sys.path:
    sys.path.append(module_path)

In [3]:
import time
from utils import get_data
from ppr import topk_ppr_matrix

In [7]:
!wget --show-progress -O reddit.npz https://ndownloader.figshare.com/files/23742119

--2023-06-19 19:45:28--  https://ndownloader.figshare.com/files/23742119
Resolving ndownloader.figshare.com (ndownloader.figshare.com)... 54.217.124.219, 52.16.102.173, 2a05:d018:1f4:d003:1c8b:1823:acce:812, ...
Connecting to ndownloader.figshare.com (ndownloader.figshare.com)|54.217.124.219|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/23742119/reddit.npz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIYCQYOYV5JSSROOA/20230620/eu-west-1/s3/aws4_request&X-Amz-Date=20230620T024528Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=5f3e350328617f9416fe526371c566e6842050fc6319f706879b18c2bfc8af03 [following]
--2023-06-19 19:45:28--  https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/23742119/reddit.npz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIYCQYOYV5JSSROOA/20230620/eu-west-1/s3/aws4_request&X-Amz-Date=20230620T024528Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signat

In [8]:
start = time.time()
(adj_matrix, attr_matrix, labels,
 train_idx, val_idx, test_idx) = get_data(
        f"reddit.npz",
        seed=0,
        ntrain_div_classes=20,
        normalize_attr=None
)
try:
    d = attr_matrix.n_columns
except AttributeError:
    d = attr_matrix.shape[1]
nc = labels.max() + 1
time_loading = time.time() - start
print(f"Runtime: {time_loading:.2f}s")

Runtime: 8.96s


In [5]:
import torch
import sklearn
from ogb.nodeproppred import PygNodePropPredDataset
from torch_geometric.utils import from_scipy_sparse_matrix, to_scipy_sparse_matrix
import scipy.sparse as sp
import numpy as np
from torch_geometric.utils import contains_self_loops, add_remaining_self_loops

dataset = PygNodePropPredDataset('ogbn-products', root='/data/gangda/ogb', )
data = dataset[0]
split_dict = dataset.get_idx_split()
train_idx = split_dict['train'].numpy()

edge_index = data.edge_index
edge_index = add_remaining_self_loops(edge_index)[0]
adj_matrix = to_scipy_sparse_matrix(edge_index)
adj_matrix = adj_matrix.tocsr().astype(np.float32)

In [269]:
%%time
alpha = 0.261
eps = 1e-5
topk = 150

topk_train = topk_ppr_matrix(adj_matrix, alpha, eps, train_idx, topk)
topk_train

CPU times: user 17min 51s, sys: 4.77 s, total: 17min 56s
Wall time: 8.95 s


<196615x2449029 sparse matrix of type '<class 'numpy.float32'>'
	with 29175655 stored elements in Compressed Sparse Row format>

In [6]:
ppr_matrix = torch.load('/home/gangda/workspace/graph_engine/intermediate/{}_ppr_matrix.pt'.format('ogbn-products'))

In [276]:
%%time
ppr_matrix2 = torch.empty((topk_train.shape[0], topk), dtype=torch.long)
for bid in range(topk_train.shape[0]):
    idx, weight = from_scipy_sparse_matrix(topk_train[bid])
    vals, order = weight.sort(descending=True)
    idx = idx[1][order]

    ppr_matrix2[bid, :idx.shape[0]] = idx
    ppr_matrix2[bid, idx.shape[0]:] = bid
ppr_matrix2

CPU times: user 33.2 s, sys: 278 ms, total: 33.5 s
Wall time: 33.5 s


tensor([[      0,  152857,  194591,  ..., 1113367,  354784,  191440],
        [      1,   89825,  151342,  ..., 2322836,  612708, 1464001],
        [      2,  488076, 1598820,  ..., 1514525, 2392288,  130654],
        ...,
        [ 196612,   84625,  233866,  ...,  315242,  106030,  794339],
        [ 196613,  231391, 2329437,  ...,  196613,  196613,  196613],
        [ 196614,   79421,  142290,  ...,  485966,  792063,  449220]])

In [281]:
import numpy as np

# batch_index = torch.randperm(train_idx.shape[0])[:1024]
batch_index = torch.tensor([171084, 112197, 137846, 116634, 64054, 122823, 130182, 130749]) # compair with shadow

shadow_ppr = [
    torch.tensor([    606,    5316,   38338,   43576,   46869,   53798,   57126,
         60027,   63729,   88129,   90170,   96196,   97958,  109661,
        123949,  131041,  137516,  139374,  148984,  150534,  171084,
        179538,  186082,  186102,  196395,  231721,  252271,  258579,
        318606,  333441,  334259,  352528,  405063,  417995,  418636,
        474880,  479302,  486479,  533302,  533315,  542731,  574119,
        582372,  614273,  632221,  659670,  671155,  676588,  696208,
        714455,  754942,  768048,  784807,  789422,  803326,  811555,
        846037,  879383,  911483,  951766,  954051,  954597,  988672,
       1000193, 1040589, 1044601, 1059208, 1060585, 1063526, 1082073,
       1098016, 1100400, 1112197, 1124389, 1127969, 1169397, 1171616,
       1171907, 1178304, 1191061, 1207644, 1207750, 1271644, 1276590,
       1277513, 1294473, 1297004, 1315504, 1337373, 1361091, 1365356,
       1373561, 1396971, 1412811, 1425132, 1448641, 1453532, 1466280,
       1476109, 1489462, 1508770, 1510106, 1524170, 1533708, 1542930,
       1585129, 1596504, 1603739, 1640855, 1652065, 1658049, 1722550,
       1724869, 1760811, 1773814, 1777515, 1777660, 1818156, 1825751,
       1858333, 1860786, 1864078, 1867155, 1929825, 1929916, 1992307,
       1998184, 2032994, 2077256, 2077319, 2079167, 2100451, 2143786,
       2144316, 2151505, 2200741, 2208221, 2217362, 2256406, 2267591,
       2268483, 2293353, 2304212, 2308792, 2315776, 2345308, 2349582,
       2377756, 2405469, 2435765]),
    torch.tensor([[   2863,    9839,   15050,   19433,   23210,   27708,   28541,
         31246,   36633,   60604,   62887,   65925,   75790,   86128,
         88360,   96828,  100120,  106672,  107228,  110908,  112197,
        117377,  121054,  121644,  126151,  127460,  140549,  141812,
        145587,  145604,  149418,  149502,  151088,  161995,  165195,
        180272,  195375,  214131,  215777,  252559,  275655,  281714,
        282112,  290266,  316911,  320692,  378095,  402841,  412729,
        437528,  440192,  454953,  455829,  461784,  471585,  481450,
        495054,  520428,  569110,  613667,  638347,  666644,  675034,
        703663,  704427,  725043,  732899,  735296,  736471,  739043,
        755486,  770691,  800820,  823438,  839961,  857560,  878983,
        884229,  932450,  967281,  980673,  998106, 1058682, 1063531,
       1066775, 1071437, 1090789, 1116509, 1135462, 1181667, 1200244,
       1225707, 1239972, 1302190, 1354941, 1357267, 1367154, 1370082,
       1409757, 1431883, 1458692, 1475306, 1496673, 1535078, 1541245,
       1590037, 1594047, 1635648, 1648758, 1677002, 1677233, 1677988,
       1724497, 1733632, 1747371, 1785132, 1816006, 1847033, 1871928,
       1883115, 1885867, 1937350, 1994281, 2004673, 2015532, 2037552,
       2047633, 2109314, 2119734, 2134644, 2134662, 2143891, 2148550,
       2149287, 2154872, 2173168, 2176627, 2235361, 2239656, 2250513,
       2250875, 2266633, 2288595, 2302794, 2310498, 2344925, 2390435,
       2391353, 2411415, 2447574]]),
    torch.tensor([[   3884,   16692,   17848,   19949,   20943,   21877,   33526,
         40435,   44422,   47796,   48497,   51470,   53913,   58483,
         62430,   63735,   65129,   66346,   68674,   68977,   74907,
         78354,   80458,   90990,   92132,   95238,   96442,   97765,
         99091,  102376,  104698,  105095,  111305,  112548,  119496,
        121035,  121724,  125637,  136063,  137846,  138637,  145466,
        148068,  149223,  151197,  151285,  155666,  157569,  169192,
        179973,  181951,  187245,  187791,  188424,  189344,  191653,
        191772,  196497,  201074,  204025,  211767,  214900,  219504,
        224072,  233301,  249907,  358695,  383291,  401350,  479671,
        567190,  581782,  614349,  623794,  648415,  683167,  684606,
        705594,  726540,  735920,  767172,  778501,  807434,  842171,
        855997,  929135,  930976,  960068,  972157,  985521,  990177,
       1005575, 1098451, 1187794, 1263135, 1276869, 1314065, 1334435,
       1364157, 1378345, 1398673, 1564623, 1625181, 1673535, 1723420,
       1738390, 1777926, 1796947, 1826332, 1836583, 1897674, 1909893,
       1961447, 1970567, 1985078, 2028808, 2055455, 2123861, 2128571,
       2132289, 2160640, 2161282, 2237635, 2259824, 2260910, 2367121]]),
    torch.tensor([[    174,    1750,    6207,   22867,   26130,   26458,   31467,
         42847,   46076,   47135,   48885,   52839,   53711,   55627,
         58077,   60972,   61828,   62126,   62743,   76060,   91600,
         92976,   96191,  102951,  104519,  104528,  109053,  116634,
        128359,  134975,  136201,  140030,  141849,  143523,  144140,
        148621,  150740,  162717,  168973,  169097,  169860,  174420,
        179150,  180781,  186329,  186915,  193720,  193774,  202342,
        203882,  213634,  213796,  219761,  220060,  226015,  227688,
        229794,  232241,  232597,  261428,  267258,  347964,  349024,
        356355,  395829,  417139,  426634,  466229,  505584,  541870,
        559326,  586015,  598566,  617378,  619694,  657009,  667829,
        681543,  687297,  709671,  748587,  750215,  762091,  796910,
        804874,  818141,  853293,  853702,  855099,  897564,  916143,
        969195, 1005506, 1050574, 1064528, 1090720, 1141230, 1153140,
       1198780, 1212813, 1246492, 1307813, 1326195, 1329507, 1349523,
       1355025, 1391342, 1408564, 1424501, 1446348, 1465928, 1470573,
       1515406, 1518740, 1635776, 1647314, 1661461, 1661890, 1666766,
       1688022, 1728974, 1800417, 1836502, 1837459, 1857487, 1861840,
       1883826, 1896613, 1906794, 1930531, 1943940, 2039924, 2096970,
       2112333, 2124524, 2135855, 2138885, 2148841, 2166385, 2177864,
       2244592, 2313472, 2316441, 2340413, 2345802, 2354980, 2357200,
       2377255, 2405165, 2416715]]),
    torch.tensor([[   2181,    7698,    8207,   10983,   11422,   14948,   18202,
         18900,   24397,   26903,   38898,   43129,   46111,   46393,
         47365,   48450,   52816,   59277,   59623,   62254,   64054,
         65689,   65708,   65733,   66379,   66397,   71478,   71929,
         82828,   92860,   93316,   93876,   97726,   99354,   99388,
        107183,  115886,  118473,  120891,  123874,  126889,  127911,
        128196,  130157,  132524,  132913,  132986,  138082,  139566,
        146339,  148944,  157194,  157965,  161989,  162537,  162792,
        163879,  164174,  165487,  169554,  171497,  172737,  175201,
        179957,  181891,  186241,  188386,  192668,  214927,  216159,
        221934,  227269,  227916,  293277,  299914,  311672,  320460,
        330105,  344435,  367758,  379275,  413736,  414073,  420427,
        424999,  481168,  503052,  661295,  685585,  691183,  729968,
        730121,  738824,  793586,  828768,  903596,  987065, 1076458,
       1092754, 1106400, 1120798, 1122008, 1133683, 1137731, 1148362,
       1151076, 1209475, 1239034, 1283500, 1346045, 1354123, 1356225,
       1357915, 1375922, 1390877, 1434039, 1437222, 1461937, 1474662,
       1502305, 1529766, 1569997, 1571872, 1581428, 1584316, 1585430,
       1586976, 1649194, 1665500, 1729377, 1744843, 1767540, 1818195,
       1911890, 2019279, 2042313, 2060078, 2066939, 2123695, 2171917,
       2176942, 2192767, 2223419, 2252679, 2287960, 2317992, 2370580,
       2383059, 2391127, 2423312]]),
    torch.tensor([[   3638,   10217,   23286,   26018,   27388,   28174,   31885,
         36394,   43743,   45547,   60826,   66328,   78447,   78828,
         79394,   81612,   87572,   97804,   98274,   99069,   99695,
        103272,  118517,  120536,  122823,  123294,  123812,  127044,
        134027,  135566,  146887,  149463,  162138,  164828,  167358,
        169331,  177198,  177424,  192529,  198382,  210301,  211167,
        216888,  218188,  224518,  260181,  284748,  324571,  354080,
        368289,  445962,  457940,  506577,  519614,  529085,  558209,
        569032,  579193,  620333,  636013,  664876,  665313,  667583,
        691635,  705670,  724359,  738995,  744517,  814887,  838324,
        873592,  896102,  952634,  957013,  974526,  987560, 1001884,
       1015006, 1018941, 1027494, 1031534, 1095165, 1128686, 1132510,
       1145129, 1146107, 1191124, 1194172, 1231700, 1253713, 1264188,
       1267252, 1283494, 1321730, 1340718, 1345734, 1387277, 1390579,
       1414951, 1416661, 1499582, 1507507, 1511524, 1514809, 1527478,
       1530239, 1548064, 1565029, 1568309, 1575510, 1576575, 1581385,
       1648229, 1652209, 1659780, 1743757, 1758222, 1778009, 1780247,
       1787067, 1788837, 1807926, 1822892, 1833721, 1836613, 1851145,
       1852432, 1882890, 1894964, 1906918, 1920730, 1948407, 2020041,
       2038633, 2063091, 2124338, 2149218, 2154578, 2156290, 2156362,
       2230809, 2255956, 2277141, 2310082, 2330551, 2352141, 2357377,
       2389156, 2389232, 2393590]]),
    torch.tensor([[   3898,    7198,   16882,   17788,   19430,   22164,   23056,
         23232,   23625,   25634,   30207,   35275,   35379,   37879,
         40105,   40546,   42364,   46212,   50335,   58859,   59844,
         63213,   66161,   68810,   69001,   69480,   69709,   71616,
         72063,   74382,   74646,   76251,   78317,   84665,   96307,
         97206,   98007,  102103,  105340,  107017,  115067,  119524,
        130182,  131080,  136491,  136964,  144290,  148709,  149504,
        152031,  155071,  161869,  163605,  177323,  180892,  181746,
        184906,  189034,  199373,  225479,  228428,  277890,  295463,
        382237,  447933,  470467,  481964,  497686,  497711,  502484,
        525861,  603841,  666416,  676228,  703777,  704536,  760278,
        770723,  796778,  818130,  876271,  900170,  907275,  927132,
        953372,  967986,  986979, 1080793, 1102579, 1112323, 1161499,
       1163759, 1185561, 1196734, 1212331, 1236184, 1280269, 1312090,
       1331957, 1353662, 1382369, 1394171, 1421956, 1454380, 1500122,
       1571377, 1590032, 1606726, 1616571, 1698983, 1702615, 1755556,
       1781482, 1840184, 1852736, 1853516, 1886572, 1917239, 1919109,
       1947490, 1977232, 1978842, 2009240, 2036279, 2059119, 2059680,
       2066326, 2070957, 2094647, 2104250, 2109289, 2112446, 2122546,
       2135625, 2152645, 2154202, 2176666, 2188812, 2210384, 2210801,
       2255817, 2258810, 2307078, 2314151, 2320660, 2342287, 2343540,
       2372598, 2425107, 2448864]]),
    torch.tensor([[   6222,    6251,    6268,    7296,   10588,   11145,   15417,
         16511,   20952,   21437,   21720,   25005,   32210,   32598,
         33255,   38843,   41492,   50061,   58896,   61115,   62735,
         64870,   65999,   70400,   72903,   74089,   75973,   76026,
         76832,   80122,   81675,   85569,   86718,   86970,   90106,
         90134,   92013,   97023,   97108,   98078,  107187,  108055,
        111736,  112638,  121554,  124241,  124370,  125624,  127373,
        129807,  129893,  130749,  142731,  145867,  146708,  150824,
        151435,  152372,  155996,  156405,  156767,  157809,  160665,
        161910,  167580,  170537,  171759,  173016,  173851,  175338,
        178624,  180264,  195225,  197482,  198567,  198696,  198942,
        203058,  214260,  218585,  228173,  228997,  341695,  383742,
        400165,  418829,  424121,  427091,  447866,  461709,  507888,
        698911,  798487,  836781,  892154, 1081300, 1084031, 1107592,
       1121145, 1135364, 1221334, 1258255, 1273891, 1293074, 1309694,
       1338520, 1372122, 1377538, 1380713, 1384349, 1453199, 1457487,
       1467081, 1474994, 1518215, 1542457, 1542741, 1548980, 1552649,
       1564253, 1653834, 1673178, 1717108, 1738934, 1751805, 1766540,
       1829955, 1837460, 1905512, 1914379, 1948321, 1948749, 2028565,
       2031083, 2073091, 2132533, 2176578, 2176934, 2190671, 2203444,
       2242442, 2243360, 2302481, 2343492, 2344023, 2354508, 2356640,
       2374541, 2389262, 2410762]]),
]

total_intersect, total_num = 0, 0
for i, bid in enumerate(batch_index.tolist()):
    # idx, weight = from_scipy_sparse_matrix(topk_train[bid])
    # pprgo_idx = idx[1].unique()

    pprgo_idx = ppr_matrix2[bid].unique()

    # engine_idx = ppr_matrix[bid].unique()
    engine_idx = shadow_ppr[i].unique()
    total_num += max(pprgo_idx.shape[0], engine_idx.shape[0])
    total_intersect += np.intersect1d(pprgo_idx, engine_idx.view(-1)).shape[0]

print(f'{total_intersect/total_num:.3f}')

0.892


In [281]:
import numpy as np

# batch_index = torch.randperm(train_idx.shape[0])[:1024]
batch_index = torch.tensor([171084, 112197, 137846, 116634, 64054, 122823, 130182, 130749]) # compair with shadow

total_intersect, total_num = 0, 0
for i, bid in enumerate(batch_index.tolist()):
    idx, weight = from_scipy_sparse_matrix(topk_train[bid])

    vals, order = weight.sort(descending=True)
    pprgo_idx = idx[1][order]
    print(vals)
    print(pprgo_idx)

    engine_idx = ppr_matrix[bid]
    print(engine_idx)
    print(np.setdiff1d(pprgo_idx, engine_idx))
    print()

    total_num += max(pprgo_idx.shape[0], engine_idx.shape[0])
    total_intersect += np.intersect1d(pprgo_idx.unique(), engine_idx.view(-1).unique()).shape[0]

print(f'{total_intersect/total_num:.3f}')

ModuleNotFoundError: No module named 'pydev_jupyter_utils'

In [8]:
import os.path as osp

ppr_dir = '/home/gangda/workspace/graph_engine/intermediate'
ppr_matrix2 = torch.load(osp.join(ppr_dir, 'ogbn-products_pprgo_ppr_matrix.pt'))

In [161]:
from torch_sparse import SparseTensor

edge_index = torch.load(osp.join('/home/gangda/workspace/graph_engine/data/ogbn-products-p2', 'dgl_edge_index.pt'))
edge_index = add_remaining_self_loops(edge_index)[0]
rowptr, col, _ = SparseTensor.from_edge_index(edge_index).csr()

tensor([        0,       175,       265,  ..., 126167004, 126167014,
        126167053])

In [80]:
def to_edge_index(rowptr, col):
    row = torch.arange(rowptr.size(0) - 1, dtype=col.dtype, device=col.device)
    row = row.repeat_interleave(rowptr[1:] - rowptr[:-1])
    return torch.stack([row, col], dim=0)

new_ei = to_edge_index(rowptr, col)

torch.Size([2449030])

In [124]:
nonz_idx = (ppr_matrix[:, 0] - torch.arange(2449029)).nonzero().view(-1)
ppr_matrix[nonz_idx]

tensor([[1568893,    4342,   24071,  ..., 1145885, 1954975, 1629447],
        [  24071,    5439, 1568893,  ...,    5439,    5439,    5439],
        [  24071,   15853, 1568893,  ...,   15853,   15853,   15853],
        ...,
        [ 308484, 2447908,  256251,  ..., 1273984,  947892, 1487095],
        [1483544, 2447941,  236294,  ..., 2447941, 2447941, 2447941],
        [2101520, 2448099, 1537121,  ..., 2448099, 2448099, 2448099]])

In [ ]:
def to_edge_index(rowptr, col):
    row = torch.arange(rowptr.size(0) - 1, dtype=col.dtype, device=col.device)
    row = row.repeat_interleave(rowptr[1:] - rowptr[:-1])
    return torch.stack([row, col], dim=0)

In [ ]:
edge_index

In [163]:
from torch_geometric.utils import subgraph
from torch_geometric.data import Data
from pyg_lib.sampler import subgraph as libsubgraph

# bid = 72485
bid = 5439
# bid = 171084

subset, inv = torch.cat([torch.tensor([bid]), ppr_matrix[bid]]).unique(return_inverse=True)
ego_index = inv[0]

ego_rowptr, ego_col, _ = libsubgraph(rowptr, col, subset, return_edge_id=False)
sub_edge_index = to_edge_index(ego_rowptr, ego_col)

# sub_edge_index = subgraph(subset, edge_index)[0]
# subset2, sub_edge_index = sub_edge_index.unique(return_inverse=True)

ego_data = Data(data.x[subset],
                sub_edge_index,
                y=data.y[bid],
                ego_index=ego_index
                )
ego_data

Data(x=[139, 100], edge_index=[2, 523], y=[1], ego_index=1)

In [170]:
edge_index[1][edge_index[0] == 2425635]

tensor([ 129315,  155015,  172061,  190068,  349557,  354311,  737390, 1023978,
        1026859, 1249940, 1565452, 1654691, 2062203, 2080520, 2164034, 2265264,
        2425635])

In [171]:
subset[138], subset[54]

(tensor(2425635), tensor(737390))

In [164]:
sub_edge_index

tensor([[  0,   0,   1,  ..., 138, 138, 138],
        [  0,  86,   1,  ...,  20,  54, 138]])

In [151]:
rptr = torch.tensor([0, 0, 1, 1, 2])
c = torch.tensor([0, 2])
subg = libsubgraph(rptr, c, torch.tensor([0, 2, 3]), return_edge_id=False)
to_edge_index(subg[0], subg[1])

tensor([[2],
        [1]])

In [153]:
ei = torch.tensor([[1, 3],[0, 2]])
subgraph(torch.tensor([0, 2, 3]), ei)[0].unique(return_inverse=True)

(tensor([2, 3]),
 tensor([[1],
         [0]]))

In [48]:
from torch_geometric.utils import remove_self_loops, add_self_loops

# edge_index = remove_self_loops(edge_index)[0]
add_self_loops(edge_index)[0].shape

torch.Size([2, 126167053])

In [51]:
subset, inv = torch.cat([torch.tensor([bid]), ppr_matrix[bid]]).unique(return_inverse=True)
subset, inv

(tensor([72485]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0]))